aString = "\n\tHola" # \n and \t only with double quotes
aNumber = 2
anotherNumber = 3.14
bigNumber = 12301484019481
negativeNumber = -324
aBoolean = true
theOtherBoolean = false
anArray = [2, 3, 4, 'hola', 2.4, [34, 12], true]
myObject = (name: 'Fran', country: 'Spain') # JSON notation
otherObject = name: 'Fran', country: 'Spain', european: true
